version: "3.7"
services:
    web:
        build: .
        container_name: flask
        restart: always
        environment:
          - USER_NAME=Dani
        ports:
            - "5000:5000"
        volumes:
            - .:/pers
        depends_on:
            - redis
    redis:
        image: redis
